### ISSUE TITLE
[README] Incorrect Coverage Status

### ISSUE THREAD

**Issue by ashmaroli** [algolia/jekyll-algolia#104]
The README is currently displaying incorrect Coverage status for the `develop` branch:

[![coverage develop](https://img.shields.io/badge/dynamic/json.svg?label=coverage%3Adevelop&colorB=&prefix=&suffix=%25&query=$.coverage_change&uri=https%3A%2F%2Fcoveralls.io%2Fgithub%2Falgolia%2Fjekyll-algolia.json%3Fbranch%3Ddevelop)](https://coveralls.io/github/algolia/jekyll-algolia?branch=develop)

While the actual status is:

[![Coverage Status](https://coveralls.io/repos/github/algolia/jekyll-algolia/badge.svg?branch=develop)](https://coveralls.io/github/algolia/jekyll-algolia?branch=develop)

**Comment by pixelastic** [comment]
Thanks for noticing that. I wanted to have two badges, one for `master` and one for `develop` on the readme. Coveralls doesn't allow customising the text of the badges AFAIK, so I uses shields.io as a proxy for that.

The API endpoint I'm using on coveralls.io is https://coveralls.io/github/algolia/jekyll-algolia.json?branch=develop, but it seems to be stuck for some reason on an old build entry (one that was coming from a PR actually).

I'm going to use the badge you linked, this seems more reliable.

**Comment by ashmaroli** [comment]
> I'm going to use the badge you linked, this seems more reliable.

That was the badge recommended by https://coveralls.io/github/algolia/jekyll-algolia

**Comment by pixelastic** [comment]
✔ Done

![image](https://user-images.githubusercontent.com/283419/48777058-d3c4a500-ecd1-11e8-9139-5063012126e0.png)

I removed the double master/develop coverage. I'd rather display less information but keep them accurate than too much and inaccurate :)
