### ISSUE TITLE
Error: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by luispuerto** [algolia/jekyll-algolia#105]
## I want to report a bug:
I know that is is a duplicate of #90 but since I can open that one... 

### What is the current behavior?

When running `bundle exec jekyll algolia` i get
```
Error:  undefined method `split' for nil:NilClass
```

doing `--trace`

```
Processing site...
Rendering to HTML (100%) |=============================================================================================|
Extracting records (100%) |============================================================================================|
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.5.0/bin/jekyll)
NoMethodError: undefined method `split' for nil:NilClass
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll/algolia/shrinker.rb:37:in `fit_to_size'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:141:in `block in push'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:140:in `map!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:140:in `push'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:37:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll-algolia.rb:75:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.4.7/lib/jekyll/commands/algolia.rb:31:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/exe/jekyll:15:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/bin/jekyll:23:in `load'
  /usr/local/lib/ruby/gems/2.5.0/bin/jekyll:23:in `<top (required)>'
```
In my case, the issue is cause by this [line](https://github.com/luispuerto/luispuerto.net/blob/9ff3b13b38ff24f613bf3eec6780d8bdaff5bccb/_includes/tagcloud.html#L2) 

That I use to create a [tag cloud in my site](https://luispuerto.net/archive/#tags).

Can you give me a hand why I'm getting this error? it's clearly related to the size of the index, but does the tag cloud really increase de size that much? 

### What is your expected behavior?

No error, clearly.... 

### Git repository to reproduce the issue:

https://github.com/luispuerto/luispuerto.net

### Ruby version used:

ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

### Jekyll version used:

jekyll 3.7.4 (since I want to keep compatibility with github pages) 

-----

Any help is appreciated

**Comment by pixelastic** [comment]
Hello @luispuerto and thanks for the report.

I'll try to have a look at this shortly.

**Comment by luispuerto** [comment]
right now I can index because I set a file exclusion in `_pages/archive.md`

**Comment by pixelastic** [comment]
I had a look at your repo and managed to reproduce the issue, thanks a lot.

There was indeed a bug when the plugin was trying to automatically shrink down the size of records that were too big to be pushed. I was trying to reduce the size of a key that was not existing in your case, generating an error.

I just release v1.4.9 that now correctly handle this case, and I've improved the error message displayed to guide users on how to solve it. In your case I think excluding the archive page from indexing is the right solution to the problem. This page does not really contain any relevant content you'd want to be accessible through search. But at least now the error message will give you pointers on how to do this :)

Thanks for helping me make the plugin better

**Comment by luispuerto** [comment]
yeah! now it works!

**Comment by luispuerto** [comment]
>This page does not really contain any relevant content you'd want to be accessible through search.
I somehow agree, somehow disagree... I don't want the page to be indexed with all the tags and categories, because it would be stupid, but I definitely would love the page to show up in results if someone search the term archive. 

It would be great to be possible to set sections of pages not indexable.

**Comment by pixelastic** [comment]
> I definitely would love the page to show up in results if someone search the term "archive".

That's a fair point. The current plugin architecture makes this hard to achieve, though.

One possible ~hack~ workaround, would be to use the [nodes_to_index](https://community.algolia.com/jekyll-algolia/options.html#nodes-to-index) option. It allows you to define what parts of the pages to index. As it accepts any CSS selector, if you set it to `p:not(.exclude-from-search)`, it would index all `<p>` paragraphs, except the ones with the class `.exclude-from-search`.

You could then modify your archive page to add this class to the parts you want to exclude. This is more or less a way to _set sections of pages not indexable_.

Hope that helps

**Comment by luispuerto** [comment]
thanks a lot @pixelastic! I think that would do. I just tried and it work like a charm!
