### ISSUE TITLE
can't push algolia API

### ISSUE THREAD

**Issue by semasuka** [algolia/jekyll-algolia#111]
I am building a blog using Jekyll and I have integrated algolia into. I was working just fine before but since 2 weeks ago I can't build the algolia API.

Please help me I have tried to search online on the issue but I have not found a solution to it. this is the error message I get

```bash
[✗ Error] Invalid credentials

The jekyll-algolia plugin could not connect to your application ID using the API
key your provided.

Make sure your API key has access to your XXXXXXXXXX application.
It should also have the rights to push to the following indices:
   - Machine Learning Blog
   - Machine Learning Blog_object_ids

You can find your API key in your Algolia dashboard here:
   https://www.algolia.com/licensing
```

**Comment by pixelastic** [comment]
This issue has been fixed through email. The problem was wrongly-encoded quotes in the `ALGOLIA_API_KEY`

**Comment by ilan-perez** [comment]
I still have this issue. What is the fix for this?

**Comment by Haroenv** [comment]
In the case it was

> The problem was wrongly-encoded quotes in the ALGOLIA_API_KEY

Could you check whether you have the right format for that key?
