### ISSUE TITLE
Don't show results when the page loads

### ISSUE THREAD

**Issue by frankmeeuwsen** [algolia/jekyll-algolia#112]
## I want to report an issue:
When I follow the tutorial to include the frontend of Algolia search on my blog, all the results are loaded when the page is loaded. I would expect an empty searchbar that only gives results when a search-query is typed in the search bar. 

Are there configuration options in Instantsearch and/or Algolia that just show the searchbar on load and give back results when a search is initiated? 

### Ruby version used:

ruby 2.4.4

### Jekyll version used:

3.8.5

**Comment by pixelastic** [comment]
Hello,

You can find more details on how to configure this behavior in the InstantSearch documentation here: https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/js/#handling-empty-queries

Hope that helps :)
