### ISSUE TITLE
Is the project still under active development?

### ISSUE THREAD

**Issue by nfrankel** [algolia/jekyll-algolia#136]
Hi guys,

Just wanted to check if the project is still under active development. From what I see, the last commit (not the last release) was on Dec. 2018. This means 6 months ago at the time of this writing.

I'm starting to get a bit worried: @pixelastic left (see <https://github.com/pixelastic> description "Previously at @algolia"), and nobody seems to have taken on the project.

First, thanks @pixelastic for your work on that project!
Now, could someone from @algolia please step in and tell us what's the roadmap for it?

**Comment by pixelastic** [comment]
Hey @nfrankel and thanks for the question.

You're not the only one wondering what the status of this project is. Algolia and I are currently discussing the best way to address this.

The gist is that I'm no longer working at Algolia (so no professional drive to work on this) and no longer use Jekyll myself (so not personal drive either). I thought I could keep working on it on my free time, but the truth is that I've moved on to other projects and motivations and I can't maintain this project as much as I'd like to. Algolia is keeping an eye on it and providing support in a best-effort kind of way, but the truth on their side is that they don't have anyone commited to it either.

So, we're discussing maybe officially end the Algolia support for this plugin, so at least people know what to expect, and move the ownership to the community.

As things currently are, I see two solutions:
- You'd like Algolia to keep maintaining it: make your voice heard. If they see how many people are using, they might find some time to give it some love.
- You'd volunteer to take ownership of the repo: let us know. We (Algolia and I) would be happy to hand you the keys, guide you through the codebase, and give you access to all the tools you need to keep the project growing.

**Comment by DirtyF** [comment]
This gem is currently used by 3000 people, so I hope Algolia sees some value in it keeping the plugin in low maintenance mode.

**Comment by nfrankel** [comment]
First, thanks again for your great work on that @pixelastic, and thanks for the clarification.

I find myself in nearly the same position as you: I'm not a Ruby developer, I'm just a simple Jekyll user who found Algolia the best way to provide search features on his website. Hence, option 2 is not really an option for me.

As @DirtyF mentioned, there are a lot of people using the Gem, so I believe (hope?) that @algolia see the value in at least maintaining the plugin.
