### ISSUE TITLE
fatal: 'jekyll algolia' could not be found.

### ISSUE THREAD

**Issue by infominer33** [algolia/jekyll-algolia#139]
### What is the current behavior?

A few months ago I had no problem setting up and building an index by following instructions that came with Minimal Mistakes. I did have problem integrating that with my site, but figured I'd give it another go, with a complete fresh site \ install.

So I go ahead and add `gem 'jekyll-algolia'` to my gem file (when it didn't work I came here to see that the instructions were the same as I was following from minimal mistakes setup)

This time, instead of easily building an index, I encountered:

`fatal: 'jekyll algolia' could not be found. You may need to install the jekyll-algolia gem or a related gem to be able to use this subcommand.` 

Of course I did install the gem, and tried all type of hacky ideas.. including following the same exact instructions a few different times.

### Git repository to reproduce the issue:

https://github.com/didecentral/didecentral.github.io

Nothing to see there, since I'm just trying getting set up locally...

### bundle install output

Shooting in the dark, I tried even specifying a pull that some have found useful...

```
source 'https://rubygems.org'
gem "minimal-mistakes-jekyll"

gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-include-cache"
gem "jekyll-mentions"
gem 'html-proofer'
gem "jekyll-redirect-from"
gem 'jekyll-algolia'', github: 'algolia/jekyll-algolia', ref: 'refs/pull/126/head''
```
**Output**:
```
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.3
Using public_suffix 3.1.1
Using addressable 2.6.0
Using json 2.2.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.5
Using algolia_html_extractor 2.6.1
Using httpclient 2.8.3
Using algoliasearch 1.24.0
Using bundler 2.0.2
Using colorator 1.1.0
Using colorize 0.8.1
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.11.1
Using ethon 0.12.0
Using multipart-post 2.1.1
Using faraday 0.15.4
Using filesize 0.2.0
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using html-pipeline 2.11.1
Using mercenary 0.3.6
Using parallel 1.17.0
Using typhoeus 1.3.1
Using yell 2.2.0
Using html-proofer 3.9.3
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using sass-listen 4.0.0
Using sass 3.7.4
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.2.1
Using kramdown 1.17.0
Using liquid 4.0.3
Using pathutil 0.16.2
Using rouge 3.7.0
Using safe_yaml 1.0.5
Using jekyll 3.8.6
Using progressbar 1.10.1
Using verbal_expressions 0.1.5
Using jekyll-algolia 1.4.9 from https://github.com/algolia/jekyll-algolia.git (at refs/pull/126/head@ff6440d)
Using jekyll-data 1.0.0
Using jekyll-feed 0.12.1
Using sawyer 0.8.2
Using octokit 4.14.0
Using jekyll-gist 1.5.0
Using jekyll-include-cache 0.2.0
Using jekyll-mentions 1.5.1
Using jekyll-paginate 1.1.0
Using jekyll-redirect-from 0.15.0
Using jekyll-sitemap 1.3.1
Using jemoji 0.11.0
Using minimal-mistakes-jekyll 4.16.5
```
maybe that's not helpful, so here's the output following a vanilla install

### Ruby version used:

`ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]`

### Jekyll version used:

`jekyll 3.8.6`

---

I see this repo is somewhat inbetween...  so I don't expect a fast resolution, but would love to have a clue, because Algolia is the best possible option for enabling search with static sites that I've heard of, and is potentially enabled for the multitude of Minimal Mistakes users..

I struggled a lot playing around w dependency versions.. if anyone has ideas for a workaround that would be cool.

one thing I noticed, is that whether I specify using '1.0' or not.. bundler has its own mind of what version to install.. but i'm still a newb just figuring everything out.

Thanks!

**Comment by Floppy** [comment]
I'm taking a look at this - it doesn't seem like the gem is even being *loaded* by jekyll, though I'm not sure why. Other plugin commands (like `jekyll import`) are working fine.

**Comment by ashmaroli** [comment]
To use the `jekyll algolia` command, the gem has to be loaded at runtime.
Move the gem-listing into the `:jekyll_plugins` group in your Gemfile:
```ruby
# Gemfile

group :jekyll_plugins do
  gem 'jekyll-algolia', github: 'algolia/jekyll-algolia', ref: 'refs/pull/126/head'
end
```
And then just run
```
bundle exec jekyll algolia
```

*(On an unrelated issue, there are unnecessary single-quotes around the `jekyll-algolia` listing in your Gemfile: `gem 'jekyll-algolia'', github: 'algolia/jekyll-algolia', ref: 'refs/pull/126/head''`)*

**Comment by Floppy** [comment]
Having copied the gemfile lines from above and pasted them into my repo, I still get `fatal: 'jekyll algolia' could not be found. You may need to install the jekyll-algolia gem or a related gem to be able to use this subcommand.` It's very odd...

**Comment by ashmaroli** [comment]
@Floppy Is your `Gemfile` in the PWD?
The above won't work if your Gemfile is in a superdirectory of current-directory.

**Comment by Floppy** [comment]
Nope, current directory. I've added `jekyll-import` in there as well to test that I'm installing commands from gems right, and it works fine. I'm missing something obvious, I'm sure, but I'm currently stumped as to what that might be!

**Comment by Floppy** [comment]
OMG. I've just found it. I was using `gems.rb` instead of `Gemfile`, and while everything else worked, the algolia command didn't! I have no idea why, but renaming the files has fixed it. Thanks for the inspiration, @ashmaroli. I'll try to work out where that bug lies, whether here or in core Jekyll.

**Comment by ashmaroli** [comment]
@Floppy I wouldn't call it a bug per se. When using plugins that provide new `jekyll` subcommands, Jekyll explicitly looks for the group `:jekyll_plugins` in `Gemfile` at PWD. `gems.rb` is a relatively new concept brought by Bundler 2.0.

Therefore, neither jekyll-3.8.x nor the upcoming `jekyll-4.0.0` will work with a `gems.rb`.
Perhaps in Jekyll 4.1.0 (no promises though).

**Comment by ashmaroli** [comment]
The reason `jekyll-import` works either ways is because that plugin has been *"blessed"* with core-support. The only other plugins with this *"blessed"* status are: `jekyll-compose` and `jekyll-docs`.

**Comment by Floppy** [comment]
That's fair - but, if I wanted to fix that, it looks like Jekyll is the place to go. Thanks!

**Comment by infominer33** [comment]
yes!! it's official and confirmed. This was not a bug, merely an operator error.

```
source 'https://rubygems.org'

group :jekyll_plugins do
    gem 'jekyll-algolia', '~> 1.0'
    gem 'jekyll-paginate'
    gem 'jekyll-sitemap'
end
```
current gemfile everything works fine and Algolia is asking for my credentials.

Thank You for the fix and the discussion, both!
