### ISSUE TITLE
AwesomePrint alters Logger color luminance

### ISSUE THREAD

**Issue by ashmaroli** [algolia/jekyll-algolia#14]
While `Jekyll::Algolia::Logger` modifies logged output when running the `jekyll algolia` command, `require "awesome_print"` ***brightens*** the colors for Jekyll Logger levels.

This is not documented (and probably not something I'd want when I decide to use this plugin)

**Comment by pixelastic** [comment]
Hmm, it looks like Jekyll is adding some `.green`, `.red` methods to every `String`. And `awesome_print` is actually doing the same thing, but with different ANSI codes.

I would say it's bad practice on both sides extending a generic type like this. I'll see if I can actually remove `awesome_print` as I'm not really using it (apart for debug purposes)

**Comment by pixelastic** [comment]
I remove `awesome_print` from the deps in `develop`

**Comment by ashmaroli** [comment]
Thank you for looking into this.
To clarify, Jekyll doesn't add a color to *every string*.. but, the strings do respond_to certain color-methods

messages from `Jekyll.logger.warn` are colored yellow.
messages from `Jekyll.logger.error` and `Jekyll.logger.abort_with` are colored red. 

That's it. No more. No less.
Messages from other Jekyll.logger levels are non-colored and can be colored by the developer-consumer. They're free to create custom Jekyll-loggers.

Jekyll makes this extension possible via the `colorator` gem

**Comment by ashmaroli** [comment]
> have them not overwrite the method if it already exists

That sounds like a practical solution since both these gems add methods to core Ruby class `String`

Regarding `jekyll-algolia`, or any jekyll plugin, the plugin and its dependencies are loaded *after loading Jekyll and its dependencies*. So, in this case, `awesome_print` overrides `colorator` which is what bugged me because a Jekyll plugin (secondary to Jekyll) should ideally just *extend Jekyll* not alter existing behavior.
And if a plugin does alter existing behavior anyways, then it should be clearly documented.

**Comment by pixelastic** [comment]
As I've removed `awesome_print` from the codebase, I think I'll pass on submitting bugs to those two repos for now. If I feel I need to re-include `awesome_print` again I'll make sure to open the relevant issues, and at least document the behavior if I can't work around it.
