### ISSUE TITLE
Using tags with Jekyll plugin ?

### ISSUE THREAD

**Issue by splotsh** [algolia/jekyll-algolia#160]
Hello,

Wondering how best I could use tags (as described here https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-tags/) with the Jekyll Algolia plugin ?

Thanks
Ben

**Comment by Haroenv** [comment]
You can set up `attributesForFaceting` with categories or other attributes which are coming from your pages. Do you have a reproducible example where I can try out your indexing?

**Comment by splotsh** [comment]
Nothing at this point that is accessible. I will look into attributesForFaceting - thanks!
