### ISSUE TITLE
Issue with Jekyll collections

### ISSUE THREAD

**Issue by jdwallace12** [algolia/jekyll-algolia#161]
Hi there, it seems my collections within Jekyll are indexing, since I see them within my index in the Algolia dashboard but I  am not seeing them in my results, am I missing something obvious?  Thanks!

**Comment by Haroenv** [comment]
Hi @jdwallace12, I see you opened and closed this issue, is it solved?

**Comment by jdwallace12** [comment]
@Haroenv , sorry for the noise! I think I figured out the issue.  I am using algolia search with autocomplete and I think it has to do with the facetFilters.  If I wanted to show collections and pages mixed together would I use something like facetFilters: ["type:page", "type:document"]
