### ISSUE TITLE
object ids get deleted when content of page changes

### ISSUE THREAD

**Issue by rishankHashout** [algolia/jekyll-algolia#187]
hey , 
I am using algolia's rules where I pin the objects ids of specific url. But if the content on that page is changed the object id is delete and rules does not works.
How to tackle this problem ?
Thanks

**Comment by Haroenv** [comment]
Using Hooks, you should be able to create a stable objectID based on your criteria instead of the current logic: https://community.algolia.com/jekyll-algolia/hooks.html#before-indexing-each

**Comment by rishankHashout** [comment]
the stable objectID work well when content of page is changed , but as we have frequent insertion and deletion of pages the same issue is encountered.

**Comment by rishankHashout** [comment]
i want to pin the record which is from particular url , as we want to show this url in results on empty query but when the content is changed in that url the object id is changed and it doesn't work as expected.

**Comment by Haroenv** [comment]
Instead of pinning, you could do optional filtering if the query is empty: https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/how-to-promote-with-optional-filters/ That way you only need a stable attribute, not stable objects completely. Hope that helps!

**Comment by rishankHashout** [comment]
yes , that worked
