### ISSUE TITLE
Log message when the plugin is pushing records to Algolia [Feature Request]

### ISSUE THREAD

**Issue by ashmaroli** [algolia/jekyll-algolia#21]
Currently, the plugin *doesn't* log a standby message before pushing records to Algolia.
I expect to see something (non-verbose log msg) like the following..
```
Pushing records to Algolia...
✔ Indexing complete
```
similarly, when it errors:
```
Pushing records to Algolia...
[✗ Error] Invalid credentials

The jekyll-algolia plugin could not connect to your application ID using the
API key your provided.

Make sure your API key has access to your {application_id} application.

You can find your API key in your Algolia dashboard here:
   https://www.algolia.com/licensing
```

**Comment by pixelastic** [comment]
Could you check the latest `develop` and let me know if you like the output better? I added a stand by message when stuff was actually pushed, and added a "Nothing to index" message if your content is already up to date.

As for errors, I would rather only display the standby message when we actually start pushing things to the API. The error you are getting is early than that, when trying to get a list of the content already in the index. It's not technically _pushing_ records, but _reading_ them.

**Comment by ashmaroli** [comment]
The standby message just before pushing looks good for now. So technically, this request ticket has been resolved.. but..
in non-verbose mode, there's a period of *silence* between the reading of config file and outputting the above standby message, when nothing is output to the terminal.

So, i'd like to extend this feature request for more standby messages:
```
$ bundle exec jekyll algolia
Configuration file: [file-path]
           Algolia: Processing site...
                    Extracting records...
                    Found 9 files
                    Pushing records to Algolia...
                    Pushing 50 records
                    ✔ Indexing complete
```

I would also like to point out that the current set of messages differ between normal mode and verbose mode. I expected to see info level messages in both normal mode and verbose mode..

**Comment by pixelastic** [comment]
The period of silence is actually Jekyll building the website (converting markdown to HTML, applying layout, etc). I've added logs for 'Processing site...' and 'Extracting records...'

It's pushed to `develop`. I'll release a new version of the gem shortly

Also, info level messages should be displayed in both modes. But because the `--verbose` flags also triggers the verbose of Jekyll itself it's possible you didn't see the message in the output.
