### ISSUE TITLE
Create a JSON file when plugin runs in dry-run mode [Feature Request]

### ISSUE THREAD

**Issue by ashmaroli** [algolia/jekyll-algolia#22]
Allow users to verify what data is actually pushed to Algolia

### Expectation
```
$ bundle exec jekyll algolia --dry-run

==== THIS IS A DRY RUN ====
  - No records will be pushed to your index. You can verify data that
    would be pushed by inspecting the file below.
  - '[index-name]-[hash].json' has been saved to your source directory [source-path]
```
with its contents being a **`pretty_generate`** dump of JSON record data

**Comment by ashmaroli** [comment]
`'[index-name]-[hash].json'` in the post above is just a suggestion. It can be named anything as you see fit.
Since the contents of the file cannot be pushed without running the `Indexer` again, it may be overwritten in subsequent dry-run. Therefore, the `-[hash]` aspect in the filename can be replaced with a `.algolia` sub-extension..

For example: if my `index-name` was `test-run`, then the resulting file would be:
```
test-run.algolia.json
```
its contents being a **`pretty_generate`** dump of JSON record data

**Comment by pixelastic** [comment]
Hmm, that's an interesting feature. Could you tell me more about your use-case?

I'm unsure if this should be part of `--dry-run` or if we should not add a new flag for that. Something like `--output-file` or `--export` so it could be used outside of dry run.

**Comment by ashmaroli** [comment]
my use case is that I would like to verify what data is actually going to be pushed to Algolia. So I simply run the command with the necessary switch and voila! the JSON data has been formatted and dumped into a file for me to read through..

**Comment by pixelastic** [comment]
I've been thinking about this feature and even if I see how it can be useful, I don't want to integrate too many options for specific use-cases. Instead, I think it's the perfect use-case for using the [hooks](https://community.algolia.com/jekyll-algolia/hooks.html#before-indexing-all).

What you can do is create a new file in your `_plugins` directory. For example `_plugins/algolia.rb` and add the following content:

```ruby
require 'json'

module Jekyll
  module Algolia
    module Hooks
      def self.before_indexing_all(records)
        index_name = Configurator.algolia('index_name')

        File.write(
          "#{index_name}-records.json",
          JSON.pretty_generate(records)
        )

        records
      end
    end
  end
end
```

It will write to a json file the list of records before pushing them. If you combine it with `--dry-run` it will still create the file but won't push anything, allowing you to have a look at it. You can add more complexity if you want by using `Configurator.dry_run?` from the hook to check if `--dry-run` was passed or not.

I'll mark this as resolved, and if more people come asking for this feature I'll consider integrating this snippet in the doc or baking it in the plugin directly.

In any case, thanks for the feedback.

**Comment by msemp** [comment]
Thanks, @pixelastic , for the detailed info and code to use the hooks. I was wishing for this feature, and  it was easy to create the .rb file as instructed and to see all the JSON data.
