### ISSUE TITLE
Split `jekyll algolia` into two commands

### ISSUE THREAD

**Issue by ashmaroli** [algolia/jekyll-algolia#23]
I feel that command `jekyll algolia` indexing records and pushing data to a cloud server is a source of security concerns.

- The user has no idea what data has been collected and pushed
- The user has no idea if the connection between their terminal and remote is secure / encrypted / open to Man-in-the-middle attacks.

One way I can think of is to split the functionality into two commands and output more messages to the user terminal

- One command **builds the current site, and indexes records (without checking the remote index)**. This command doesn't require an Internet connection and will result in writing the data to a file on disk in a special directory (say `./.algolia/` akin to how GIT writes a commit, only readily accessible by the user)
- The other command **first establishes a secure connection to remote Algolia, then reads remote index and then finally pushes the latest local index in `.algolia/` directory to remote.**
This command would not initiate a Jekyll Build process and purely search-index-centric.

By using a special directory to hold the index data, the user can inspect the search data (in JSON), will more likey add it to their `.gitignore` or similar files and therefore, the directory can also be a safe place to hold their `_algolia_api_key` file.

/cc @DirtyF

**Comment by DirtyF** [comment]
AFAIC I am not so concerned about security as I only index already public information. And I trust Algolia engineers for that. 😄 

As the plugin allows to configure what to index or not, I 'm all for the _setup and forget it_ approach. 

Like `rm` the command could have a `-i` option that displays info like the diff on the last two indexes and ask for confirmation before pushing to Algolia, but I'm fine with the current Algolia's dashboard to inspect the index.

Here I bet most users will want to setup CI and forget about it.

**Comment by pixelastic** [comment]
Hey, thanks for the idea. I'm more leaning toward @DirtyF here, I'd like the plugin to have the most straightforward API as possible. Being able to have all the data indexed just by running `jekyll algolia` is a large part of that DX.

That being said, and as you mentionned in another issue, being able to build the records without pushing them, or push records without having to build the whole website could also be interesting, as it could allow for more custom workflows.

I'd rather keep the default behavior as `jekyll algolia`, but allow for `--output` and `--input` arguments to define where to output the JSON instead of pushing it, and which JSON to take as input instead of rebuilding everything (exact name of the arguments to be defined, of course).

Would that fit your need @ashmaroli?

**Comment by ashmaroli** [comment]
Thanks for looking into this Tim.
Its more of my "concern" rather than my "need" .. because communicating with a remote endpoint is a source of security leaks.
Not that I do not trust the engineers at Algolia, but that as an end user I have no guarantee that the data being pushed to Algolia is encrypted and via a secure channel that a middle-man cannot intercept and, route a copy of the data being pushed, to his private database..

**Comment by pixelastic** [comment]
I understand your concern, but I don't see how splitting it in two commands would help. If the plugin was malicious, splitting the command in two commands won't you do much good as the plugin could still push something completely different than what was saved in the JSON in the first phase.

I would say the fact that the whole code is open-source and that all the Algolia endpoints are HTTPS should be enough guarantee.

**Comment by ashmaroli** [comment]
You've raised some valid arguments above.
What the plugin could do is output appropriate logger messages.. e.g.
```
$ bundle exec jekyll algolia
Building records..
Inspecting your records at [index_url]..
Pushing new records to [index_url]
Success! Indexing complete!
```
(just an example to give you the idea.. so please excuse the order of messages..)

**Comment by pixelastic** [comment]
Fair point. This might be something I'll add to the `--verbose`. I'll reopen to remember.

**Comment by pixelastic** [comment]
I've updated messages like this:

Normal mode:
```
Processing site...
Extracting records...
Updating records in index my_index...
Pushing 264 records
✔ Indexing complete
```

Verbose mode
```
Processing site...
Extracting records...
Found 54 files
Indexing mode: diff
Updating settings
Inspecting existing records in index my_index...
Updating records in index my_index...
Pushing 264 records
✔ Indexing complete
```

**Comment by ashmaroli** [comment]
Thanks @pixelastic. I haven't tested the current `master`, but the changes you've outlined above is definitely an improvement.. :+1:

**Comment by pixelastic** [comment]
The gem is actually released on RubyGems if you want to try. I haven't yet announced it officially, but it's there ;)
