### ISSUE TITLE
Combine `diff` and `atomic` mode

### ISSUE THREAD

**Issue by j-f1** [algolia/jekyll-algolia#24]
From the readme:

> By default, the plugin will try to be smart when pushing content to your index: it will only push new records and delete old ones insted of overwriting everything.
> ...
> The drawback is that [`atomic` mode] will consume much more operations as you will have to push all your records to a new index each time.

Why couldn’t atomic mode only push changed, new, and deleted records to the `*_tmp` index (like diff mode), then swap the two indices? Example:

```yaml
# my-index
- a
- b
- c
# my-index_tmp
- a
- b
- c

# => add `d`
#   - add `d` to `my-index_tmp`
#   - swap the two indices
# my-index
- a
- b
- c
- d
# my-index_tmp
- a
- b
- c

# => add `e`
#   - add `d` and `e` to `my-index_tmp`
#   - swap the two indices
# my-index
- a
- b
- c
- d
- e
# my-index_tmp
- a
- b
- c
- d
```

**Comment by pixelastic** [comment]
Oh, that's actually a pretty neat idea. Best of both worlds. By doing it that way we have an atomic indexing (no time with an incomplete index) while using only few operations.

Only downside is that the plan still need to hold twice the number of records for a short amount of time (which might make the users reach their quota on free plans). That being said, I'll investigate and see how this is possible to do

**Comment by pixelastic** [comment]
I've updated the `atomic` value to start with a fresh copy of the existing index instead of recreating from scratch. You can find the PR here: https://github.com/algolia/jekyll-algolia/pull/35

Let me know if you could give it a go and see how it performs

**Comment by pixelastic** [comment]
Thanks a lot for the idea @j-f1. I've implemented something very similar to your original idea in v1.1.0. It now actually does all the diff in place on the current index, in one atomic move.

As this is a better way than both the `diff` and `atomic` modes, I've now set it as the default way of pushing records and I have deprecated `indexing_mode`
