### ISSUE TITLE
Pages at /blog/pages/*/ are not excluded

### ISSUE THREAD

**Issue by dzello** [algolia/jekyll-algolia#26]
If you go to [dzello.com](https://dzello.com/) and search for `test`, you will see some pagination pages in the search results.

Source code for the repo is at [dzello/dzello-dot-com](https://github.com/dzello/dzello-dot-com).

**Comment by pixelastic** [comment]
Fixed in `develop`. The plugin was only excluding the default pagination pages. It now correctly exclude pagination pages defined with `paginate_path`.
