### ISSUE TITLE
Clean the footnote links

### ISSUE THREAD

**Issue by nhoizey** [algolia/jekyll-algolia#27]
Paragraphs indexed and listed in results sometimes contain footnote links that are rendered as plain text, which is not optimal:

![image](https://user-images.githubusercontent.com/78213/34033267-cd12c96c-e179-11e7-866e-3558bb957815.png)

Example here:
https://nicolas-hoizey.com/recherche.html?q=posse

**Comment by pixelastic** [comment]
That's a good but I don't think I can add a generic solution directly inside the plugin.

Instead, I would sugget using the [hooks](https://community.algolia.com/jekyll-algolia/hooks.html#before-indexing-each). That's exactly what they are for: editing the records before they are pushed.

In your case, you could add a `_plugins/algolia.rb` to your repo (the file name has no importance, but it has to be in `_plugins`) with the following content:

```ruby
module Jekyll
  module Algolia
    module Hooks
      def self.before_indexing_each(record, node)
        node.css('sup[id],.reversefootnote').each(&:remove)
        record[:html] = node.to_html
        record[:content] = node.content

        record
      end
    end
  end
end
```

The `before_indexing_each` hook is documented on the website, but basically it will take the record and the HTML node (as a Nokogiri object) as arguments and should return the new record.

Here what I'm doing is removing any footnotes and reversed footnotes nodes from the node, and then updating the html and textual content of the record before sending it back.

Hope that helps :)
