### ISSUE TITLE
Synonyms are cleared when doing an atomic push

### ISSUE THREAD

**Issue by pixelastic** [algolia/jekyll-algolia#29]
Originally opened at https://github.com/algolia/algoliasearch-jekyll/issues/62

When doing an atomic push, synonyms (and query rules) are not correctly kept. I'll need to first grab the synonyms from the index and then re-push them.

**Comment by infomofo** [comment]
Is there a lazy update flag in this new jekyll-algolia plugin? Or is there a different command I should be using for incremental index updates other than "bundle exec jekyll algolia"

I upgraded from the old jekyll plugin and now it seems to be resetting my ranking rules in my algolia dashboard every time there's an index push.

**Comment by pixelastic** [comment]
Hello,

The default behavior of the new plugin is the lazy update (only updating what needs to be updated instead of updating everything). I've now named those "indexing modes", and they are documented and explained [here](https://community.algolia.com/jekyll-algolia/indexing-modes.html). This should only have an impact on records, not settings, though.

As for settings, every time you run `jekyll algolia` it will update (overwrite) your settings. It will merge the plugin hard-coded needed index settings with your own (see the [`settings` option](https://community.algolia.com/jekyll-algolia/options.html#settings)) and push that to the index. It means that if you did some manual changes in your Algolia dashboard, they might be overridden. In that case, you should update your settings directly from the `settings` option I mentioned above.

If it does not work as expected, don't hesitate to open an issue with more details about what you did and what you expected to happen, and I'll have a look.

**Comment by infomofo** [comment]
Ah I see now- I will say this documentation is not really very clear, a sample jekyll config on the readme page would go a long way.

**Comment by pixelastic** [comment]
Thanks for the feedback, I'm keeping this issue open until I've fixed the documentation.

What I think I'll do is:

- Add a mention in the Getting Started guide (and README) that changes done through the Dashboard should be discouraged and added to the `settings` option instead.
- Add a mention in the `settings` documentation explaining that every manual change done through the dashboard should be added here as well.

WDYT?

**Comment by pixelastic** [comment]
@infomofo I've created a new issue (#34) to reference your specific issue. I think I can find a way to make changes made in the Dashboard stay between pushes.

**Comment by infomofo** [comment]
Thanks so much for the quick response on this - I really appreciate it. I think either of these will work as long as the implementation is clearly documented for a new or migrating user.

**Comment by pixelastic** [comment]
This should be fixed in v1.1.0 as we no longer create temporary indices
