### ISSUE TITLE
Allow settings update from the dashboard

### ISSUE THREAD

**Issue by pixelastic** [algolia/jekyll-algolia#34]
Follow up of #29.

The current behavior of configuring settings can be confusing. Users can edit settings directly from the Algolia dashboard, or configure them in the `settings` key of `_config.yml`. If changed from the dashboard, they will get overwritten on the next push.

I might be able to improve this behavior by only overwriting settings when something is defined in the `settings` option. If nothing is set, we keep the settings as-is, allowing people to tweak them through the Dashboard.

I will still need to push some default settings the first time even if no `settings` are set, but for that I can simply check if the index exists or not. If it does not, I create one with default settings. If it exists, I don't touch it

**Comment by rayrutjes** [comment]
> I will still need to push some default settings the first time even if no settings are set, but for that I can simply check if the index exists or not. If it does not, I create one with default settings. If it exists, I don't touch it.

I would go one step further. Even if settings are provided, if the destination index already index, then don't re-push the settings.

It is then the job of the user to keep the settings file in sync with whatever manual change was made to the index.

So far this is the best workflow I've ever experienced.

**Comment by pixelastic** [comment]
If I do that, then only the first push to Algolia will use the `settings` provided in `_config.yml`, right? Meaning that people would edit the `settings`, push, and nothing would happen? This does not seem right. I'd rather have settings committed in the repo having precedence over settings manually set in the dashboard.

**Comment by pixelastic** [comment]
This should be fixed in v1.1.0

**Comment by EdenKupe** [comment]
Hey,

I'm encountering an issue where pushing to Algolia even with no settings in `_config.yml` defined overwrites anything I configured via the dashboard. Is this the expected behavior?

**Comment by pixelastic** [comment]
@EdenKupe This is partly expected. 

The plugin comes with its own set of settings needed for it to work correctly (things like ranking formula and default fields to search, etc). Those settings are hard-coded and will be merged with any custom settings you define in `_config.yml` and will overwrite anything you set in the dashboard.

**But**, the plugin _should_ detect that it is going to overwrite something you manually changed in the dashboard and _should_ let you know, and display in its output the value it is about to overwrite, and giving you instructions on how to "save" those changes in `_config.yml` so they are not lost forever.

If you're not having this warning message and still having dashboard settings overwritten, then we have a bug. Would you be able to give us more details about your workflow and the settings that were overwritten?

_As a side note, I no longer work at Algolia, so my support time and tooling is a bit more limited than it used to be. I'm invoking @julienbourdeau and @aseure to keep an eye on the issue as well ;)_

**Comment by juhaelee** [comment]
@Haroenv 

Finding that not having settings or having settings as empty is overriding the configuration in the dashboard. 

For example, adding something to `searchableAttributes` gets cleared due to the plugin
