### ISSUE TITLE
Setting a default `index_name`?

### ISSUE THREAD

**Issue by pixelastic** [algolia/jekyll-algolia#37]
## I want to suggest a feature:

**What is your use case for such a feature?**
I want to make the getting started guide as short as possible. I want people trying the plugin for the first time to be up and running quickly.

**What is your proposed API? Is this a new option? A new behavior?**
The current getting started asks user to define their `application_id` and `index_name` in the settings. The application ID is generated by Algolia, but the index name can be whatever they want.

Maybe we could provide a default index name (eg. `jekyll`) when people don't fill that value, so they don't have to think about "where can I find this value?". Of course, it can be overwritten.

**Comment by DirtyF** [comment]
Great idea, maybe you could use `{{ site.name }}` as the default index name?

**Comment by pixelastic** [comment]
I'm a bit concerned that this might seem too magical. If people update their site name, their front-end search might just stop working because they won't be pushing to the correct index.

I think we should use a more static value because people that won't fill this value won't care about how it's actually named. So `jekyll` might be explicit enough

**Comment by Haroenv** [comment]
If it's documented to use `{{ site.name }}` in the InstantSearch config, I think that would seem quite nice though

**Comment by pixelastic** [comment]
Actually, it's documented to use `{{ site.algolia.index_name }}` in the InstantSearch config, so it's reading the value from `_config.yml`.

It's ok to define a default value if this is empty for the purposes of the plugin, but here we want to have a default value used in the front-end as well. I might require to overwrite the `site` values. I think it's doable.

**Comment by pixelastic** [comment]
Fixed in `develop`. 

I actually did not implement a default value. Instead, I made the documentation more straightforward (setting `jekyll` as the default value in the doc). Automatically setting the value in the global site was a bit too magical (and too much code). I'd rather be straightforward and transparent in what is going on.
