### ISSUE TITLE
Add instructions on how to display the results with InstantSearch.js

### ISSUE THREAD

**Issue by pixelastic** [algolia/jekyll-algolia#4]
A generic tutorial of using InstantSearch.js with to display results. We could use a common theme (Hyde is  good candidate) explaining how to integrate the front-end. We should not maintain an official fork of Hyde, simply reuse its code as an example.

**Comment by DirtyF** [comment]
I wonder if @mmistakes would be interested in adding search to one of his popular jekyll themes.

**Comment by pixelastic** [comment]
That would be awesome actually.

I would rather have themes officially supporting the plugin than forking an existing one.

@mmistakes if you would like to participate, I'd be happy to help. Otherwise, just pointing me to which theme you think would benefit the most from a search interface, and I'll submit a PR.

**Comment by pixelastic** [comment]
✔ Done on the default minima theme: https://community.algolia.com/jekyll-algolia/blog.html

I'll be posting an issue on https://github.com/mmistakes/jekyll-theme-basically-basic/issues to see if @mmistakes would be interest in adding search to the theme.
