### ISSUE TITLE
Unicode Symbols

### ISSUE THREAD

**Issue by jonaprieto** [algolia/jekyll-algolia#45]
## I want to suggest a feature:

Search strings that contain Unicode symbols.

### What is your use case for such a feature?

Many things that I write contains symbols that are not included in a default charset,
they are Unicode symbols like ∀, λ, →, and among others.  I use these symbols
because my writing is about math and other stuff related. So, I would like
to have the chance to search by using those symbol that appears in the post
as in a normal paragraph or into a block code that it's pretty common.

### What is your proposed API? Is this a new option? A new behavior?

The new option could be specified in the _config.yml file:

```
algolia:
  ...
  index_name:     'notes'
  index_unicode_symbols: true
```

**Comment by pixelastic** [comment]
Hello @jonaprieto,

Searching for UTF8 characters **should** work by default. Could you share a link to your git project / live website / application ID, so I can try on my side?

**Comment by pixelastic** [comment]
I confirm that the search on those symbols is not currently working. I'm investigating.

**Comment by pixelastic** [comment]
So, by default the engine is considering those characters as punctuation, and won't allow searching for them.

The good news is that you can override the defaults, using the [separatorsToIndex](https://www.algolia.com/doc/api-reference/api-parameters/separatorsToIndex/) option of the index.

```yaml
algolia:
  settings:
    separatorsToIndex: '∀λ→'
```

You have to manually add all the special characters you might use, and then you'll be able to search for them. Hope that helps :)

**Comment by jonaprieto** [comment]
Yes, I tested thanks, one last question, algolia indexes also inside the code blocks?

**Comment by pixelastic** [comment]
The plugin only index the HTML elements that are matching your [nodes_to_index](https://community.algolia.com/jekyll-algolia/options.html#nodes-to-index) configuration value (default is all `<p>`). If you also want to index codeblock, you might want to edit that to `p,pre` (for example, if your codeblocks are in `<pre>` tags).

**Comment by jonaprieto** [comment]
I'm been testing your solution from your last reply but I got this now:

```
$ jekyll algolia
...
jekyll 3.7.2 | Error:  undefined method `[]' for nil:NilClass
```

Searching Unicode seems to work fairly well so far.

**Comment by pixelastic** [comment]
@jonaprieto Would you mind opening a new issue with a link to a repo where I could reproduce the issue? I tried indexing `<pre>` tags on my side and had no issue.

Thanks!
