### ISSUE TITLE
Make the plugin known

### ISSUE THREAD

**Issue by pixelastic** [algolia/jekyll-algolia#5]
- [x] Post it to JAMStack-fr
- [x] Tell Netlify about it
- [x] Tell CloudCannon about it
- [x] Add it to the [official list of plugins ](https://jekyllrb.com/docs/plugins/)
- [x] Update it from the [Awesome Jekyll](https://github.com/planetjekyll/awesome-jekyll-plugins) list

**Comment by DirtyF** [comment]
- [x] [post on talk.jekyllrb.com](https://talk.jekyllrb.com/t/jekyll-algolia-plugin-v1-0/1179) 😄 
- [x] posted on thenewdynamic.org Slack channel 👍 
- [x] add it on https://www.thenewdynamic.org/tool/algolia/ ✅ 
- [ ] tell [Siteleaf](https://www.siteleaf.com/) ?
- [ ] tell [Foresty.io](https://forestry.io/) ?

**Comment by pixelastic** [comment]
:tada: Thanks @DirtyF!

It's still in beta mode, so I'm more looking for beta-testers right now, and I plan on doing the "real" release in two weeks. I'd like to build the website before announcing it publicly, with full documentation (especially the front-end part)

But thanks for the push, that's greatly appreciated.

**Comment by pixelastic** [comment]
PR for adding in the official Jekyll plugin list: https://github.com/jekyll/jekyll/pull/6737

**Comment by pixelastic** [comment]
Quick demo on Siteleaf.com website: https://pedantic-lamport-cb9332.netlify.com/

Suggested in https://github.com/siteleaf/siteleaf.com/issues/19
