### ISSUE TITLE
BUG: Files excluded from Algolia seems to be deleted from `_site` folder

### ISSUE THREAD

**Issue by thomasjsn** [algolia/jekyll-algolia#50]
## I want to report a bug:
Files excluded from Algolia seems to be deleted from `_site` folder.

### What is the current behavior?
When running command `bundle exec jekyll algolia` `index.html`is deletes from `_site_` folder. If I add more files to exclude in with the `files_to_exclude` config, more files are deleted. Bug seems to have appeared with the jekyll-algolia (1.1.4) version.

Update: I see that also the 404.html gets deleted.

### What is your expected behavior?
Please don't delete files in the `_site` folder.

### Commands to reproduce:
```
$ jekyll build
$ ls _site/
2015  2016  2017  2018  404.html  about  assets  electronics  feed.xml  homelab  index.html  robots.txt  search  sitemap.xml  work-area
$ ALGOLIA_API_KEY='my-key' bundle exec jekyll algolia
$ ls _site/
2015  2016  2017  2018  about  assets  electronics  feed.xml  homelab  robots.txt  search  sitemap.xml  work-area
```

### Ruby version used:
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

### Jekyll version used:
jekyll 3.7.3

**Comment by thomasjsn** [comment]
Downgraded to 1.1.2, and it does not have the same problem.

**Comment by pixelastic** [comment]
Oh, thanks for the report! This is indeed an important issue.

In 1.1.3, I updated the way files were excluded when running `jekyll algolia` to not render files that were not going to be indexed (to gain some precious seconds on large websites). I didn't expect this to actually remove existing files from `_site`.

I'm going to check that right now!

**Comment by pixelastic** [comment]
@thomasjsn Could you check with v1.1.5 I just released?

**Comment by thomasjsn** [comment]
@pixelastic  I'll give it a try tonight, can't make it before.

**Comment by thomasjsn** [comment]
Sorry, got a bit delayed. Yeah, that seems to have fixed it :)

**Comment by pixelastic** [comment]
Hurrah \o/ :tada:
