### ISSUE TITLE
Weird versioning error happening on Travis

### ISSUE THREAD

**Issue by Haroenv** [algolia/jekyll-algolia#51]
## I want to report a bug:

I tried out a few things (see recent commits), but they all failed in travis while installing the dependencies (see the [logs](https://travis-ci.org/Haroenv/blog/builds))

### What is the current behavior?

Can't install on Travis

### What is your expected behavior?

Can install on Travis

### Git repository to reproduce the issue:
 

https://github.com/haroenv/blog

### Ruby version used:

2.2 I think 

### Jekyll version used:

 3.7.3

**Comment by pixelastic** [comment]
jekyll-algolia is only compatible with Ruby versions 2.3+. Could you try upgrading your `.travis.yml` to use 2.3 instead of 2.2?

**Comment by Haroenv** [comment]
all right, missed that bit!
