### ISSUE TITLE
Use Jekyll hook to trigger index

### ISSUE THREAD

**Issue by mneumegen** [algolia/jekyll-algolia#53]
### What is your use case for such a feature?
If updating the index was triggered by a [Jekyll hook](https://jekyllrb.com/docs/plugins/#hooks) as opposed to (or addition to) a separate command, then the index would update automatically every build. 

You would want to control what environment the hook is run in. Checking if `ALGOLIA_API_KEY` exists seems like a good way to this.

### What is your proposed API? Is this a new option? A new behavior?

None. You would install the plugin, run jekyll with the `ALGOLIA_API_KEY` environment variable and it would work.

**Comment by pixelastic** [comment]
So I've given more thought to this and I think I'll have to pass on this feature for now (unless there is a lot of demand for it).

There are a few points that make it non-trivial to implement:

- Moving the logic to fit in Jekyll hook system in addition to its own `jekyll algolia` command will add a lot of complexity to the code (that I would rather avoid for now, unless absolutely necessary). Also, the way Jekyll handles post render hooks in addition to incremental builds (using local cache) seems a tricky area with hidden complexity. I would avoid going there if possible.

- Triggering the Algolia indexing based on the presence of the `ALGOLIA_API_KEY` seems dangerous to me. This would mean that there would be no way to do a normal build if the environment key is present. On platforms like Travis or Netlify, you might want to have this key present (so you can run `jekyll algolia`), but you wouldn't want this to interfere with a regular `jekyll build`. I would rather go with a new option, like `jekyll build --algolia` to trigger it instead. But I'm not sure if that would be supported by CloudCannon and solve your use-case?

- I made some great performance improvement on `develop` that should largely mitigate the performance waste of running `jekyll build && jekyll algolia`. Previously it was basically building the website twice. It is much smarter now and even if it will still have to render some files twice, it will skip most of the files that won't be actually indexed.

Overall, the ratio of work and added complexity compared to the gain (as opposed to running `jekyll build && jekyll algolia`) does not seem worth it today. Of course, I'm still open to ideas and discussion around the topic (leaning toward a `jekyll build --algolia` entrypoint), but I'm gonna put this at the bottom of the backlog for now.

Feel free to share more about your context if you have time :)
