### ISSUE TITLE
Custom collection documents with only frontmatter (no content) are not indexed

### ISSUE THREAD

**Issue by andrewsavikas** [algolia/jekyll-algolia#56]
## I want to report a bug:  
Custom collection documents that only have frontmatter (but no main content below the frontmatter) are not indexed

### What is the current behavior? 
When the plugin is run, documents in a custom collection that have no content (but do have frontmatter) are not processed. If any arbitrary content is added to a document in the custom collection, when the plugin is run again that document is successfully indexed.

### What is your expected behavior?
If a collection is set to "output: true" then all files should be indexed, even if they do not have any content in their main body (but do have frontmatter)

### Ruby version used:
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

### Jekyll version used:

jekyll 3.7.3

**Comment by andrewsavikas** [comment]
After poking around, perhaps the issue is in [extractor.rb?](https://github.com/algolia/jekyll-algolia/blob/develop/lib/jekyll/algolia/extractor.rb)
![jekyll-algolia_extractor_rb_at_develop_ _algolia_jekyll-algolia](https://user-images.githubusercontent.com/296656/37485913-377bb1da-2863-11e8-824f-1d2c3182f855.png)

**Comment by andrewsavikas** [comment]
As a workaround, if I explicitly include content in the custom post (for example, {{page.excerpt}}) then the custom post is indexed.

**Comment by pixelastic** [comment]
Thanks for the report and for taking the time to dig in the plugin code.

You're totally right in your assumptions: if the page contain no content, then it will not be indexed. The plugin actually parses the content of each page (excluding its layout) to build its list of records. If you have all your rendering done in the layout, then nothing will be saved.

I don't know if it's a bug or a feature. This is intended behavior technically, but unfortunate in that case as collections should still be indexed. I like your API proposal of indexing them if `output: true` is set, it shouldn't be too hard to add.

**Comment by pixelastic** [comment]
v1.2.3 now correctly index collections, even when they don't have a content. I've actually also fixed it for posts and pages.

Thanks for the report!
