### ISSUE TITLE
Markdown paragraphs parsed as '\n\n' leading to "Record is too big" error

### ISSUE THREAD

**Issue by evmo** [algolia/jekyll-algolia#60]
First, thank you for developing this plugin!

I'm having trouble getting the plugin to successfully index my site. `bundle exec jekyll algolia` always fails with:

`[✗ Error] Record is too big`. 

Looking at the resulting json log file, I notice that for certain markdown pages, it is failing to recognize paragraphs. Instead, it parses them as a double-newline `\n\n`. For large pages, this results in one giant `<p>` node which exceeds the 10KB limit.

Example page and log file: https://github.com/evmo/jekyll-algolia-error

`ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]`

`jekyll 3.7.3`

**Comment by pixelastic** [comment]
Thanks for the report.

Could you let me know if you changed the default value of [nodes_to_index](https://community.algolia.com/jekyll-algolia/options.html#nodes-to-index)?

If not, you might have another plugin that is getting in the way of jekyll-algolia. Would you have a repository I could clone to reproduce the issue?

**Comment by evmo** [comment]
I hadn't changed the default value of nodes_to_index

To test the idea of conflict with another plugin, I disabled the other plugins. Index+push was successful then. Then I re-added the plugins one at a time to find the conflicting one. Strangely, even after I re-added all the plugins the algolia push was still successful.

So, I am unsure what caused the issue and am now unable to reproduce it on my own machine. Sorry to waste your time.

**Comment by pixelastic** [comment]
No problem, and you didn't waste any of my time :)

I'm glad the issue is resolved, but if it ever happens again, don't hesitate to file a new issue and I'll get to the bottom of it.
