### ISSUE TITLE
Make the indexing atomic

### ISSUE THREAD

**Issue by nhoizey** [algolia/jekyll-algolia#67]
### What is your use case for such a feature?

I would like the indexing to be atomic, so that the index isn't broken when there is an issue during indexing task.

For example, I had an issue early April with one of my content being too large, and didn't notice until today that my index is now almost empty:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/78213/39510291-8906cd4a-4de9-11e8-888c-fc6334853e8f.png">

### What is your proposed API? Is this a new option? A new behavior?

New behavior, I don't think it requires a new option or setting.

**Comment by nhoizey** [comment]
I understand and agree with your aim to make it work with community plans.

Your last option with size check before pushing seems indeed the best one.

**Comment by pixelastic** [comment]
Closing in favor of #68
