### ISSUE TITLE
Fails to build `remote_theme` sites

### ISSUE THREAD

**Issue by mmistakes** [algolia/jekyll-algolia#69]
## I want to report a bug:

Running `jekyll algolia` with versions > 1.3.2 causes the build and indexation to fail. I believe this is due to changes that were made to [disable parts of the GitHub Pages gem](https://github.com/algolia/jekyll-algolia/commit/fc280c6437c978b3eb10b1c6065604ba7e7b9751) which loads plugins like `jekyll-remote-theme` that are necessary to build the site.

Because `jekyll-remote-theme` isn't installed none of the `_layouts`, `_includes`, and other theme files are loaded and Jekyll fails to build.

### Git repository to reproduce the issue:

You can see the [full log over on Travis CI](https://travis-ci.org/mmistakes/minimal-mistakes/builds/374548677#L593). This is a build with Jekyll Algolia v1.4

When I lock Jekyll Algolia to version `1.3.2` in my `Gemfile` everything [works as expected](https://travis-ci.org/mmistakes/minimal-mistakes/builds/374573299#L664). 

```
Processing site...                                                               
      Remote Theme: Using theme mmistakes/minimal-mistakes
```

**Comment by pixelastic** [comment]
Thanks for the issue!

I think your guess is correct. I recently discovered that the GitHub Pages plugin, when disabling all plugins not in the authorized list, was also disabling the use of custom plugins in `_plugins` (used by jekyll-algolia for custom hooks). This disabling was also set on every `jekyll [...]` command.

What I did was disable the GitHub pages plugin completely when running `jekyll algolia` to prevent that. It looks like it also prevented it from correctly loading its other dependencies.

Does it work if you add `jekyll-remote-theme` to your `Gemfile`? And if so, do you think that would be an acceptable workaround?

**Comment by mmistakes** [comment]
Adding `gem "jekyll-remote-theme"` to my `Gemfile` sort of works now. The remote theme is picked up by Jekyll it seems (called twice for some reason), but it's still not picking up the layouts and includes. Perhaps something else is needed in the GitHub Pages gem that is disabled.

I see a bunch of errors like this:

```
Processing site...                                                               
      Remote Theme: Using theme mmistakes/minimal-mistakes
Error reading file /home/travis/build/mmistakes/minimal-mistakes/_layouts/splash.html: No such file or directory @ rb_sysopen - /home/travis/build/mmistakes/minimal-mistakes/docs/home/travis/build/mmistakes/minimal-mistakes/_layouts/splash.html 
Error reading file /home/travis/build/mmistakes/minimal-mistakes/_layouts/home.html: No such file or directory @ rb_sysopen - /home/travis/build/mmistakes/minimal-mistakes/docs/home/travis/build/mmistakes/minimal-mistakes/_layouts/home.html 
```

I'm not sure if this affects the index file, but it does seem to generate and push it. Whether it's accurate I have no idea as it seems like the pages aren't built since it can't find the layouts to do that.

```
Progress: |====================================================================|
Progress: |====================================================================|
Settings are already up to date.                                                 
Getting list of existing records                                                 
Content is already up to date.                                                   
✔ Indexing complete   
```

Here's the full build on Travis if you needed to see it.
https://travis-ci.org/mmistakes/minimal-mistakes/builds/375031252#L458

**Comment by pixelastic** [comment]
I just released a v1.4.1 that seem to be working for me with your repo. Instead of completely disabling the `github-pages` gem, it now switch the `--safe` mode back to off (disabling the whitelist of plugins), and forces `plugins_dir` to `_plugins` (as per the defaults).

This should allow the inclusion of remote theme `include` while keeping custom hooks working. I've updated the tests on my side for most of the scenarios that I can think of, but I'd really appreciate if you could give it a try on your setup to make sure everything works as intended.

**Comment by mmistakes** [comment]
Everything looks good to me now. No errors or unintended side-effects as far as I can tell.

```
Processing site...
      Remote Theme: Using theme mmistakes/minimal-mistakes
Rendering to HTML (100%) |=============================================================================================================================================|
Extracting records (100%) |============================================================================================================================================|
Settings are already up to date.
Getting list of existing records
Content is already up to date.
✔ Indexing complete
```

**Comment by pixelastic** [comment]
Awesome. Thanks for checking!
