### ISSUE TITLE
Collection posts with no date in front matter cause indexing error.

### ISSUE THREAD

**Issue by kimfucious** [algolia/jekyll-algolia#74]
### Description

Collection posts with no date in front matter cause indexing error.  

This is similar to Issue #70 but not exactly the same, as we're dealing with collection posts.

Jekyll collection posts don't generally have a date assigned to them, by nature.  So adding a date to the front matter isn't really a desired step.

As a test:  I **can** render the date from a collection post that doesn't have a date set in front matter, using:

`{{ page.date }}`

So, **I think**, that while Jekyll is assigning dates to these collection posts under the hood, the Algolia plugin is specifically looking for a `date` variable somewhere that can't be found (unless it's in the collection post's front matter).  Because `date` is not found, when there is no `date` in front matter, an error is thrown.

The error **does not occur** with other posts/pages that don't have `date` in their front matter, including those in "_posts" (which I believe is actually a collection).  I'm gonna guess that (prior to looking at front matter) wherever Algolia is looking for `date` for these items is a different location than where the collection post `date` would be found.

### What is the current behavior?

`ALGOLIA_API_KEY=secretkey jekyll algolia` returns the following error.

```
jekyll 3.8.2 | Error:  undefined method `date=' for #<Jekyll::Document _docs/corde.md collection=docs>
Did you mean?  date
               data
```
The document mentioned in the error does not have a `date` set in the front matter.  Others that do, don't throw an error.  The error is thrown at the first collection item processed w/o `date` in the front matter.

### What is your expected behavior?

The command should run successfully and not fail on collection posts that do not have a `date` variable in the font matter.

### Git repository to reproduce the issue:
Here's the [repo](https://github.com/kimfucious/sakura/tree/search-modal), but it might be more efficient to test this on a collection post in your environment, rather than building this theme locally.

### Jekyll Algolia version used:
1.4.2

### Ruby version used: 
ruby 2.3.4p301

### Jekyll version used: 
3.8.2

**Comment by pixelastic** [comment]
Thanks for the issue.

I'll have to have a look at the repo you provided to pinpoint exactly what is going on. The error you're reporting seems that something is trying to **set** a date on your item (not read it).

My guess is that jekyll-algolia and one of your other plugins (the seo or sitemap one) are interfering with each other. Would you be able to try to disable them and see if jekyll-algolia works better?

I'll definitely have a better look at this, but won't have time until at least next week, though.

**Comment by kimfucious** [comment]
Thanks, Tim.  

No rush on my side.  I'm just trying to showcase Algolia Search in my humble Jekyll template.

At this point, you know better than I.

Having said that, both the seo and sitemap plug-ins have been around for a while.  I'm not sure what that adds after have typed it...

Again, when you have the time, try to focus on the whatever differences might exist when dealing with collection items, over otherwise "normal" posts.

All the Best,

Kim

**Comment by pixelastic** [comment]
Thanks, I definitely have a look at your repo and see what is going on :).

Thanks for the issue!

**Comment by kimfucious** [comment]
Hi Tim,

I've done some digging and found that the problem seems to be related to the jekyll-paginate-v2 plugin ~> 1.9.4

If I have the plugin installed, but I don't enable it on any collection, then Algolia indexing works fine.

It looks like @pserwylo came across a similar issue with no dates on collections and dealt with it by adding a "cautionary check", as described [here](https://github.com/sverrirs/jekyll-paginate-v2/pull/30).

At this point, I'm not sure if this is an Algolia Jekyll plugin problem, or if I should bring it up with @sverrirs.

Apparently, jekyll-paginate-v2 is being considered for official Github Pages support, so it seems likely that it's going to be the replacement for the original jekyll-paginate; but, who knows?

Kindly let me know what you think.  

In the meanwhile, I'm trying to think of a clever workaround that doesn't involve manually putting date variables into every collection post.

Thanks,

Kim

**Comment by pixelastic** [comment]
Thanks a lot for digging into this. This is really helpful.

The jekyll-algolia plugin has a few lines of code to deal with external plugins. I already automatically disable jekyll-paginate when running `jekyll algolia` (because there is no need to index the pagination page, so I can gain a few seconds of processing by just disabling the plugin). I guess I'll have to do something similar with jekyll-paginate-v2 then :)

**Comment by pixelastic** [comment]
I just had a look at your repo and I cannot manage to reproduce the issue.

I updated the `_config.yml` to point to my app/index, than I did a `bundle install` followed by a `ALGOLIA_API_KEY='XXX' jekyll algolia` and got everything working.

```
Processing site...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 3 pagination page(s)
Rendering to HTML (100%) |========================================================|
Extracting records (100%) |=======================================================|
Settings are already up to date.
Getting list of existing records
Content is already up to date.
✔ Indexing complete
```

Is there a specific branch I should try to experience the bug? Having an easy way to reproduce the error would really help :)

**Comment by kimfucious** [comment]
Hi Tim,

Thanks for the follow up.

I put dummy dates on the collection documents to prevent the error from happening.

Go into `_docs` and remove the date from any one of the file's front matter.  

Ideally, there shouldn't be a need to have a date on any collection documents.

```markdown
---
title: Algolia Search
description: How to Setup Algolia Search
category: Docs
date: 2017-07-10 15:00:00 <= delete me!
---
```

Also, the site build process is based on Gulp.  There's two more steps:

1.  yarn or npm install
2. run the `install-theme` Gulp task (e.g. yarn install-theme)

See [here](https://github.com/kimfucious/sakura#installation) for details.

This moves everything into place, does a jekyll build, and starts the server.  It might be more than you want/need to test, but it's the quickest.

**Comment by pixelastic** [comment]
Thanks for the details and for your patience while I was fixing the issue.

Turns out `jekyll-paginate-v2` is indeed trying to access and manipulate dates on documents. By default Jekyll sets the date of documents to the current build date. 

In `jekyll-algolia` I overwrote that part so all documents without a date, have `nil` as a date instead of the current date. I needed this in order to correctly know which documents were modified between two runs. But doing so was creating errors with `jekyll-paginate-v2`.

I just release v1.4.5 of `jekyll-algolia` that actually completely disable `jekyll-paginate-v2` when running `jekyll algolia`. Pagination pages won't be indexed into Algolia anyway, so I can afford to completely disable the plugin (it will make generation time faster as well). It's something that was already in place for the legacy `jekyll-paginate`, so it made sense to add it for `jekyll-paginate-v2` as well.

Let me know if v1.4.5 solves your issues. You should be able to remove dates from your documents with no more issues from now on :)

**Comment by kimfucious** [comment]
Hi Tim,

Thanks for the follow up.

1. Updated Gemfile with `gem "jekyll-algolia", "~> 1.4.5"`
2. Ran`bundle update`
3. Removed date from front matter of all collection documents.
4. Ran the algolia command to index

Success!

Nice work.  Thanks much for coming back to this.

**Comment by pixelastic** [comment]
Glad to hear it solves your issue.

By the way, let me know if you'd like me to add your theme [to the list](https://community.algolia.com/jekyll-algolia/themes.html#themes) :)

**Comment by kimfucious** [comment]
Sure, add me to the list!  Three's Company 😸

**Comment by pixelastic** [comment]
Could you give me the link to the repo you'd like to share and possibly a Twitter/Github/Website I could use as a link on your name?

**Comment by kimfucious** [comment]
Hi Tim,

The github repository is [here](https://github.com/kimfucious/sakura) with a readme that points to the the demo site [here](https://sakura.abts.io).

If you need more, kindly let me know.

Thanks again for putting in the effort to get this collections issue sorted.

**Comment by pixelastic** [comment]
Thanks for the kind words. Your theme has been added to the documentation :)
