### ISSUE TITLE
Specify index name & directory from the command

### ISSUE THREAD

**Issue by bsubedi26** [algolia/jekyll-algolia#75]
### What is your use case for such a feature?
Hello, just came across this plugin and it has been very useful so far. I have a quick question: Is it possible to specify the algolia index name and the directory(s) you want to send to that index? Something similar to: `jekyll algolia -index books -directory _books`.

The main reason for this is there are collections that are pushed to separate algolia indices and the way its currently being done is via the `_config.yml` where we specify index_name and exclude the folders we do not want to include for that index. This becomes a hassle when you have more than a few indices you want to update. Please let me know if I am missing something or if there is a better way to do this.

**Comment by pixelastic** [comment]
Hello and thanks for the issue,

You can use the `ALGOLIA_INDEX_NAME` environment variable to define the name of the index, so `ALGOLIA_INDEX_NAME=books jekyll algolia` will push to the `books` index.

There is no command line option to specify the directories, though. I would suggest creating a different `_config.yml` file for each different use-case.

That being said, you could also push all your collections into the same index, and filter on a specific one [using a facet](https://www.algolia.com/doc/guides/searching/faceting/?language=php#retrieving-facets). Authors, tags, categories and collections are automatically configured as usable for faceting.

Hope that helps :) Let me know if you'd like me to clarify any specific point.

**Comment by pixelastic** [comment]
@bsubedi26 Hope my previous answer helped you enough to move forward with your indexing of collection.

I'm going to close the issue, but feel free to comment back if there's anything I can clarify further.
