### ISSUE TITLE
Pagenation files are getting indexed.

### ISSUE THREAD

**Issue by idvorkin** [algolia/jekyll-algolia#76]
### What is the current behavior?
Pagenation files (page*) are getting indexed.

E.g. goto:  http://idvorkin.github.io/search and search for eulogy.

Notice the results that include hits with title BLOG, which are pagenation files. 

### What is your expected behavior?
Pagenation files (page*) do not get indexed. 

### Git repository to reproduce the issue:
 
https://github.com/idvorkin/idvorkin.github.io

### Ruby version used:

> ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

### Jekyll version used:

jekyll 3.7.3

**Comment by pixelastic** [comment]
Hello @idvorkin and thanks for the bug report,

There is no easy way for the plugin to know if a page is a regular page (that it should index) or a pagination page (that it should skip). I added special checks to handle the popular `jekyll-paginate` plugin (that you are using) but it seems that those checks only work if `jekyll-paginate` is added as part of the `:jekyll_plugins` group in the `Gemfile`.

I released v1.4.4 that should correctly skip pagination pages even if `jekyll-paginate` is not part of the `:jekyll_plugins` group. In your case, I would also suggest adding `index.html`, `search.html` and `categories.html` to `algolia.files_to_exclude`.

Could you let me know if v1.4.4 solves the issue for you? Thanks.

**Comment by pixelastic** [comment]
You're welcome. Glad it solved your issue.

Happy coding!
