### ISSUE TITLE
"bundle exec jekyll algolia" used to suggest which post exceeds the 10k quota in v1.4.0 but not in v1.4.3

### ISSUE THREAD

**Issue by SeraphRoy** [algolia/jekyll-algolia#77]
### What is the current behavior?

When I do `bundle exec jekyll algolia`, if a record is too big, it doesn't show me which post is it.

### What is your expected behavior?

It worked in v1.4.0, but not in v1.4.3, where before it showed me which post the record is too big.

### Git repository to reproduce the issue:
 

https://github.com/SeraphRoy/SeraphRoy.github.io and undo the last commit which add excerpt tags and will cause `bundle exec jekyll algolia` to pass.

### Ruby version used:

ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

### Jekyll version used:

jekyll 3.7.3

### Notes

Sample output from v1.4.3:

```
[jekyll-algolia] Raw error: 400: Cannot POST to
https://VQQEF0782J.algolia.net/1/indexes/*/batch: {"message":"Record at the
position 820 objectID=45a1e92a0c94fca2d619fd68bcea96ed is too big size=10065
bytes. Contact us if you need an extended
quota","position":820,"objectID":"45a1e92a0c94fca2d619fd68bcea96ed","status":400}
(400)
[✗ Error] Record is too big

The API rejected one of your records because it is too big (10.06 Kb).

Make sure the value of `max_record_size` (currently set to "10000") matches the
maximum size allowed by your current Algolia plan.
```

Sample output when I switch back to v1.4.0:

```
[jekyll-algolia] Raw error: 400: Cannot POST to
https://VQQEF0782J.algolia.net/1/indexes/*/batch: {"message":"Record at the
position 819 objectID=45a1e92a0c94fca2d619fd68bcea96ed is too big size=10065
bytes. Contact us if you need an extended
quota","position":819,"objectID":"45a1e92a0c94fca2d619fd68bcea96ed","status":400}
(400)
[✗ Error] Record is too big

The jekyll-algolia plugin could not push one of your records as it exceeds the
10 Kb size limit.

The plugin will create one record for each element matching your
`nodes_to_index` value (currently set to "p").
Each record should not weight more than 10 Kb.
One of your records weights 10.06 Kb and has been rejected.

objectID: 45a1e92a0c94fca2d619fd68bcea96ed
title:    Operating System Virtualization
url:      /2017/06/08/Operating-System-Virtualization/

Most probable keys causing the issue:
   excerpt_text (3.88 Kb), excerpt_html (3.88 Kb), html (0.84 Kb)
```

**Comment by pixelastic** [comment]
Thanks for the report and for the link to your repo, it made finding the issue much easier.

The main issue was that the way I was calculating the size of a record was wrong. I was using a simple string length, while I should have use the string bytesize (as some UTF-8 characters have a length of 1, but a larger bytesize). I fixed this and now the plugin is able to pro-actively detect if your record is going to be too big or not. It will try to shrink it down (by reducing/removing excerpts) until it fits. If it can't reduce it enough, it will warn you.

You should now be able to use v1.4.6 of the plugin, that includes the correct calculation and should automatically reduce the size of your records if needed. Let me know if it works or if you're having other issues.

Thanks!
