### ISSUE TITLE
Excluding files in custom collections

### ISSUE THREAD

**Issue by BryanSchuetz** [algolia/jekyll-algolia#86]
I don't seem to be able to exclude files within custom collections, e.g.: `_news`. Is this how it's intended to work? I see in the documentation you can exclude specific posts, I used the same syntax for my collections and it doesn't seem to work.

**Comment by pixelastic** [comment]
Hello and thanks for the report,

You should be able to exclude files from custom collections. Would you be able to share your project directory structure and the patterns you used so I can reproduce the issue on my side?

**Comment by pixelastic** [comment]
Hello @BryanSchuetz, would you mind sharing a repository where I could reproduce the issue?

**Comment by pixelastic** [comment]
I'm closing this issue for now, but don't hesitate to send a link to a repo where I could reproduce the issue and I'll get it fixed.

Thanks!
