### ISSUE TITLE
Passing an initial search value into the search-box widget

### ISSUE THREAD

**Issue by idvorkin** [algolia/jekyll-algolia#87]
## I want to suggest a feature:
*I suspect this is supported, but I can't find it in the docs :(*
I want to pre-populate the search box based on a query parameter that is the initial search.  E.g. when the user goes to ```/search&q=foo``` the search is executed with foo.

### What is your use case for such a feature?
Passing links with a pre-populated search.

**Comment by pixelastic** [comment]
Hello,

Thanks for the message. This is somehow supported, and I wanted to showcase a 404 page that would do such a thing (search the website for what is typed in the url).

I haven't tested it so I'm only suggesting this from memory, but what you'll have to do is to first read the `q` from the url, and then update the value of the input that is bound to your search with this value. Something like `document.querySelector('#my-input').value = 'your keywords'` should work.

Hope that helps :)

_I'll come back more thoroughly on this issue later when I'll have a bit more time, but I wanted to give you a potential quick workaround nonetheless_.

**Comment by idvorkin** [comment]
Thanks! The approach makes sense.  My JS/HTML isn't that strong, so I could
be making a silly mistake.  In the console, the querySelector  is returning
the correct div, but setting the value property doesn't do anything. Any
other property names to try off the the top of your head?

**Comment by pixelastic** [comment]
I did a quick test and it seems that in addition to changing the value, you'll also need to trigger an `oninput` event to let the input know that the value changed, and thus sending a new search query.

I tested the following code on https://community.algolia.com/jekyll-algolia-example/

```javascript
const input = document.querySelector('.ais-search-box--input');
input.value = "keyword";
input.dispatchEvent(new Event('input'))
```

Let me know if this works :)

**Comment by idvorkin** [comment]
Works in console. Is there a a race condition around this call happening before the search box being loaded?

**Comment by pixelastic** [comment]
Ah yes, I think it should be called after `search.start()` is called, so the library correctly listens to the input value changing.

This will trigger a first empty search though, so it might create a slight flicker effect. I will try to find a better alternative when I'll write the official tutorial :)

**Comment by idvorkin** [comment]
Looks like there's still a race. In my implementation I get the search initiated with the passed in value, then the input box is cleared (instead of remaining in the box).

**Comment by pixelastic** [comment]
@idvorkin Did you manage to get this to work? If you have a demo repo or a small playground (jsfiddle/codesandbox/etc) I could have a look

**Comment by pixelastic** [comment]
I'm going to close this issue to clean up the list. Hope you found a way around your race condition, if not, don't hesitate to post back a link with a reproduction of the issue and I'll do my best to help you figure it out.

**Comment by idvorkin** [comment]
@pixelastic Sorry for the delay.  I'm still hitting the race.  See: https://idvorkin.github.io/?q=stress

**Comment by pixelastic** [comment]
I sent a PR your way to pre-populate the field: https://github.com/idvorkin/idvorkin.github.io/pull/3

It's using the `searchParameter` option of InstantSearch to set the query; I think it's the most robust way of doing it.
