### ISSUE TITLE
Travis CI / Github pages error using 'bundle exec jekyll algolia' and following tutorial

### ISSUE THREAD

**Issue by ErwinLengkeek** [algolia/jekyll-algolia#88]
## I want to report a bug:
I am using Github Pages and wanted to integrate search using Algolia. I've followed the tutorial at
https://community.algolia.com/jekyll-algolia/github-pages.html and this repo's readme file.

### What is the current behavior?
Locally I am able to run the command 'bundle exec jekyll algolia' succesfully. Through Travis CI, the above happens.

The current behavior is that, using Travis CI, the moment the command 'bundle exec jekyll algolia' is activated, configuration file read and site processed, I get the following error(s):

`Progress: |====================================    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "{{{_highlightResult.firstname.value}}" in vendor/bundle/ruby/2.4.0/gems/algoliasearch-1.23.2/README.md
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "{{{_highlightResult.lastname.value}}" in vendor/bundle/ruby/2.4.0/gems/algoliasearch-1.23.2/README.md
==========  Liquid Exception: Liquid syntax error (line 121): Unknown tag 'feed_meta' in vendor/bundle/ruby/2.4.0/gems/jekyll-feed-0.10.0/README.md
jekyll 3.7.3 | Error:  Liquid syntax error (line 121): Unknown tag 'feed_meta'`

I've been able to fix the previous error, very similar to this, by adding jekyll-avatar to my gemfile, because it complained about unknown tag 'avatar'.

### What is your expected behavior?
Something goes wrong, and although it can be fixed by adding all the gems that it complains about, I'm confident that it won't fix the root cause. Am I missing something here perhaps? Or is something missing in the guide that I haven't figured yet?

### Ruby version used:
Ruby version: 2.4.4p296 (locally)

### Jekyll version used:
Jekyll version 3.7.3 (locally)

**Comment by pixelastic** [comment]
Hello and thanks for the report,

The way the plugin works is by pretending to build the website (generating HTML pages) just like a `jekyll build` would do, but instead of saving HTML files, it pushes content to Algolia. To do so, it has to go through all the `markdown -> html` converting process a normal build would do.

It means that the platform where you're running this would need to have all the required dependencies (even if they seem unrelated to the search feature). I can't ascertain much more from your error message, but if you manage to run it correctly locally and it fails on Travis, I guess it's because you have a version mismatch between the two.

Could you check that you are running the same Ruby version both locally and on Travis, and that you Gemfile contains all the required gems for Travis to build? Also, if you have a repository where I could reproduce the issue, that would help.

Thanks,

**Comment by ErwinLengkeek** [comment]
Hello @pixelastic ,

Thank you for your response. The version on Travis for Ruby is 2.4.1p111, locally mine is 2.4.4p296. The difference is minor, but not the same. However, I think it might not be the issue. 

The error suggests to me that the readme file of Algolia Search (vendor/bundle/ruby/2.4.0/gems/algoliasearch-1.23.2) and the readme file of Jekyll feed are being parsed by Liquid after the command 'bundle exec jekyll algolia' is executed.

After adding the option 'files_to_exclude' in my _config.yml for Jekyll, with the following options:
`  
- 'index.html'
- 'index.md'
- '**/*.tmp.html'
- '**/README.md'
`

I've ran this locally, which resulted in that that both settings and content are up to date, according to the terminal output.
When I pushed it to Git, a Travis build was started. The command was succesfull and this was (part of) the output:
`
Records to delete: 0                                                             
Records to add: 834
`

Afterwards I checked the Algolia Dashboard and noticed that it had indexed all readme's of all gems.

To replicate the issue, it happens with the following repository: https://github.com/theobald-software/theobald-software.github.io
The Algolia Application ID is 4C27F1P1UC.


Kind regards,

Erwin

**Comment by pixelastic** [comment]
Thanks a lot for the repo to reproduce the issue.

Now that you mention that Travis is trying to read markdown from gems, this reminds me [of an issue about Travis](https://jekyllrb.com/docs/continuous-integration/travis-ci/). By default, it will download all gems into a `./vendor` folder, at the root of your project.

![image](https://user-images.githubusercontent.com/283419/44659207-aedad180-aa03-11e8-8f9e-bde218bc6b7f.png)


This might cause issues with how Jekyll then builds file. Could you try to add `exclude: [vendor]` into your travis file? If that solves the issue I'll update the documentation to mention it :)

**Comment by ErwinLengkeek** [comment]
This very much explains it. It didn't occur to me to check the Jekyll documentation itself to see if it said anything about Travis CI. After adding vendor to the exclude array, it fixed the issue and deleted all the entries that weren't supposed to be there as well.

Thanks a lot for helping out @pixelastic !

**Comment by pixelastic** [comment]
Thanks to you for investigating. I'm keeping this issue open to remind myself to update the documentation
