### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by djacquel** [algolia/jekyll-algolia#95]
### What is the current behavior?
 - I fork [current development branch](https://github.com/djacquel/jekyll-algolia/commit/44f1787161104770829f4f311ba85227f9675692) 
 - I trigger a build on Travis CI
 - [It fails](https://travis-ci.org/djacquel/jekyll-algolia/jobs/441692766)

### What is your expected behavior?
I prefer to have all GREEN!!!

This is referring to last three PR ([1](https://github.com/algolia/jekyll-algolia/pull/85), [2](https://github.com/algolia/jekyll-algolia/pull/89) and [3](https://github.com/algolia/jekyll-algolia/pull/91)) that are not supposed to fail.

I guess that there is a coveralls issue :

>Coverage report sent to Coveralls.
/home/travis/.rvm/rubies/ruby-2.4.2/bin/ruby -I/home/travis/build/djacquel/jekyll-algolia/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.8.0/lib:/home/travis/build/djacquel/jekyll-algolia/vendor/bundle/ruby/2.4.0/gems/rspec-support-3.8.0/lib /home/travis/build/djacquel/jekyll-algolia/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.8.0/exe/rspec spec/jekyll-algolia_spec.rb spec/jekyll/algolia/configurator_spec.rb spec/jekyll/algolia/error_handler_spec.rb spec/jekyll/algolia/extractor_spec.rb spec/jekyll/algolia/file_browser_spec.rb spec/jekyll/algolia/hooks_spec.rb spec/jekyll/algolia/indexer_spec.rb spec/jekyll/algolia/logger_spec.rb spec/jekyll/algolia/overwrites_spec.rb spec/jekyll/algolia/progress_bar_spec.rb spec/jekyll/algolia/shrinker_spec.rb spec/jekyll/algolia/utils_spec.rb spec/spec_helper.rb spec/spec_helper_simplecov.rb --color --format progress failed

Can someone at Algolia give us some feedback on this blocking issue for Jekyll's use.

**Comment by pixelastic** [comment]
Hey, thanks for the report. 

I didn't have much time to look into the CI issues recently, but I will definitely fix it at some point. I'm sorry about that. Thanks for the reminder!

**Comment by pixelastic** [comment]
I finally fixed the tests in https://github.com/algolia/jekyll-algolia/commit/546992a2cb6ce5b472f797cc8d87d4de5c0de832. Travis should now correctly build :)

**Comment by pixelastic** [comment]
Thanks for letting me know, I'll see what is going on. This `MissingCredentialsError` should have been stubbed to always pass. I'll check.

**Comment by pixelastic** [comment]
I just pushed https://github.com/algolia/jekyll-algolia/pull/106 to force a test on a PR, and all is green. I think the issue you were having might come from an outdated branch. I merged your PR anyway, so I think I can close this issue.

Thanks for reporting it!
