### ISSUE TITLE
Pushing all markdown/html content

### ISSUE THREAD

**Issue by bsubedi26** [algolia/jekyll-algolia#96]
### What is the current behavior?
For a single markdown/html file, `jekyll-algolia` only pushes the first html element to the `html` field as a single record to the algolia index. Which means that if a single markdown file has 5 paragraphs, there will be one record created for each paragraph of content (total of 5 records).

### What is your expected behavior?
Is there a way to push all the markdown/html content of a page/markdown file to the `html` field as a single record? We're using algolia in the front end (react) to pull the whole html content of a page so having all the html content in a single field would be useful.

**Comment by pixelastic** [comment]
Hello,

This is unfortunately not possible, by design, for two reasons:
- Records stored in an Algolia index can't be larger than 10kb (20kb on paid plans). Most blog posts would exceed this limit.
- By splitting large texts into smaller chunks, we also increase the relevance of the results, displaying the exact matching part of the text that is relevant to the typed keywords.

But it's also not entirely accurate that only the first paragraph of content is pushed. All paragraphs are pushed, but only one paragraph per page is ever returned by default. If you want to get all the paragraphs and reconstruct the entirety of the html body, you should send `distinct: false` in your search parameters. It will effectively disable the grouping on the url that was forcing to return only the best matching result, and return all results for a given page.

Hope that helps, let me know if you need more information

**Comment by bsubedi26** [comment]
@pixelastic Thanks for the explanation. If we were to get all the paragraphs and reconstruct the entirety of the html body by sending `distinct: false`, how do we sort/order the html content? Is there a way to distinguish that a specific record's html is the first content of the body for a specific page?

If putting the order field to a record is not configurable out of the box, do you suggest running a hook (specifically `before_indexing_each`)?

**Comment by pixelastic** [comment]
All records actually contain a field named `custom_ranking.position` that contains an integer representing their position in the markup (the first element will have `1`, the second `2`, etc). If you have a look at the content of your index from the Algolia Dashboard you'll see those fields.

There are two issues with that in regard to what you want to achieve:
- By default, those fields are [**not** returned by the API](https://github.com/algolia/jekyll-algolia/blob/develop/lib/jekyll/algolia/configurator.rb#L32-L34) (as they are only used for ranking criterias, I thought I didn't need to return them. For clarity, the dashboard always display hidden fields). This can be changed by overwriting the `unretrievableAttributes` in your plugin `settings` config to an empty array. This will require a re-indexing.
- Not all HTML nodes are actually indexed. Only `<p‭>` and `<hX>` are by default, and although you can edit this list, some scripts are always excluded for security reasons (`script`, `iframe`, etc). This means you wouldn't be able to recreate the exact same markup through the records that are saved in the index.

I feel that even if you go through all the hassle of getting all the records and re-ordering them in your front-end, you won't be able to achieve the result you want. I'm afraid this use-case is pushing the sweet spot of Algolia a bit too much. It seems you're trying to use it as a database when it's meant to be used as a search engine, unfortunately.

The simplest solution I can think of would be to redirect users to the static page of their result, generated server side when they select a result. If you want to keep the SPA aspect of not reloading the page, then you could ask Jekyll to generate a JSON version of each of your page and fetch this to populate your data when you need to display the result.

Hope that helps :)

**Comment by pixelastic** [comment]
One small note: if your pages are small enough, you could try to hack your way in a hook to add some special records that contains the whole content of the pages and query them when you need them. For this to work you'll need to make sure the jsonified version fits under 10kb, but depending on your website it **could** work.

**Comment by bsubedi26** [comment]
@pixelastic Thanks a lot. We're going to build the html page in the front end using the value from `custom_ranking.position`. This looks like the best way to do it for now.

**Comment by pixelastic** [comment]
Glad you could find a solution :)
